package model.constants;

class Quotes {
	public static var array:Array<String> = [
		'You miss 100% of the shots you don’t take. ~ Wayne Gretzky',
		'The journey of a thousand miles begins with a single step. ~ Lao Tzu',
		'The walls between art and engineering exist only in our minds. ~ Theo Jansen',
		'The secret to getting ahead is getting started. ~ Mark Twain',
		'The greater danger for most of us lies not in setting our aim too high and falling short; but in setting our aim too low, and achieving our mark. ~ Michelangelo',
		'Assumption is the mother of all failure ~ Eugene Lewis Fordsworthe',
		'If you spend too much time thinking about a thing, you’ll never get it done. ~ Bruce Lee',
		'If you are going to doubt something, doubt your limits. ~ Don Ward',
		'Best way to predict your future is to create it. ~ Stephen R. Covey',
		'If you fail to plan, you plan to fail. ~ Benjamin Franklin',
		'Ever tried. Ever failed. No matter. Try again. Fail again. Fail better. ~ Samuel Beckett',
		'We can’t solve problems by using the same kind of thinking we used when we created them. ~ Albert Einstein',
		'It always seems impossible until it’s done. ~ Nelson Mandela',
		'Be yourself; everyone else is already taken. ~ Oscar Wilde',
		'Two things are infinite: the universe and human stupidity; and I’m not sure about the universe. ~ Albert Einstein',
		'It’s hard to beat a person who never gives up. ~ Babe Ruth',
		'Strive not to be a success, but rather to be of value. ~ Albert Einstein',
		'Be not afraid of growing slowly; be afraid only of standing still. ~ Chinese Proverb',
		'With self-discipline most anything is possible. ~ Theodore Roosevelt',
		'------------',
		'Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.\n~ Samuel Beckett',
		'Life is 10% what happens to you and 90% how you react to it. \n~ Charles R. Swindoll',
		'The walls between art and engineering exist only in our minds.\n~ Theo Jansen',
		'It is impossible to make anything foolproof because fools are so ingenious. \n~ Murphy\'s law',
		'Knowing is not enough, we must apply. Willing is not enough, we must do. \n~ Bruce Lee',
		'Showing off is the fool\'s idea of glory. \n~ Bruce Lee',
		'I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times. \n~ Bruce Lee',
		'Adapt what is useful, reject what is useless, and add what is specifically your own. \n~ Bruce Lee',
		'If you spend too much time thinking about a thing, you\'ll never get it done. \n~ Bruce Lee',
		'Having no limitation as limitation \n~ Bruce Lee',
		'If you love life, don\'t waste time, for time is what life is made up of. \n~ Bruce Lee',
		'The key to immortality is first living a life worth remembering. \n~ Bruce Lee',
		'Mistakes are always forgivable, if one has the courage to admit them. \n~ Bruce Lee',
		'It is not a daily increase, but a daily decrease. Hack away at the inessentials \n~ Bruce Lee',
		'If you spend too much time thinking about a thing, you’ll never get it done. \n~ Bruce Lee',
		'I’m not in this world to live up to your expectations and you’re not in this world to live up to mine. \n~ Bruce Lee',
		'Do not pray for an easy life, pray for the strength to endure a difficult one. \n~ Bruce Lee',
		'A wise man can learn more from a foolish question than a fool can learn from a wise answer. \n~ Bruce Lee',
		'Absorb what is useful, discard what is useless and add what is specifically your own. \n~ Bruce Lee',
		'Mistakes are always forgivable, if one has the courage to admit them. \n~ Bruce Lee',
		'To hell with circumstances; I create opportunities. \n~ Bruce Lee',
		'I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times. \n~ Bruce Lee',
		'Real living is living for others. \n~ Bruce Lee',
		'The more we value things, the less we value ourselves. \n~ Bruce Lee',
		'The more we value things, the less we value ourselves \n~ Bruce Lee',
		'If you love life, don’t waste time, for time is what life is made up of. \n~ Bruce Lee',
		'Showing off is the fool’s idea of glory. \n~ Bruce Lee',
		'Life’s battles don’t always go to the stronger or faster man. But sooner or later the man who wins, is the man who thinks he can. \n~ Bruce Lee',
		'The successful warrior is the average man, with laser-like focus. \n~ Bruce Lee',
		'Knowing is not enough, we must apply. Willing is not enough, we must do. \n~ Bruce Lee',
		'In the middle of chaos lies opportunity.\n~ Bruce Lee',
		'For it is easy to criticize and break down the spirit of others, but to know yourself takes a lifetime. \n~ Bruce Lee',
		'Be happy, but never satisfied. \n~ Bruce Lee',
		'Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it. \n~ Bruce Lee',
		'The key to immortality is first living a life worth remembering. \n~ Bruce Lee',
		'If you can dream it, you can do it. \n~ Walt Disney',
		'The future belongs to those who believe in the beauty of their dreams. \n~ Eleanor Roosevelt',
		'Aim for the moon. If you miss, you may hit a star. \n~ W. Clement Stone',
		'Don’t watch the clock; do what it does. Keep going. \n~ Sam Levenson',
		'We aim above the mark to hit the mark. \n~ Ralph Waldo Emerson',
		'Keep your eyes on the stars, and your feet on the ground. \n~ Theodore Roosevelt',
		'One way to keep momentum going is to have constantly greater goals. \n~ Michael Korda',
		'You just can’t beat the person who never gives up. \n~ Babe Ruth',
		'Start where you are. Use what you have. Do what you can. \n~ Arthur Ashe',
		'Why should you continue going after your dreams? Because seeing the look on the faces of the people who said you couldn’t... will be priceless. \n~ Kevin Ngo',
		'It does not matter how slowly you go as long as you do not stop. \n~  Confucius',
		'Only I can change my life. No one can do it for me. \n~ Carol Burnett',
		'Luck is what happens when preparation meets opportunity. \n~ Seneca',
		'Do. Or do not. There is no try. \n~ Yoda',
		'People often say that motivation doesn\'t last. Well, neither does bathing -- that\'s why we recommend it daily. \n~ Zig Ziglar',
		'Someday is not a day of the week. \n~ Denise Brennan - Nelson',
		'Hire character. Train skill. \n~ Peter Schutz',
		'Your time is limited, so don\'t waste it living someone else\'s life. \n~ Steve Jobs',
		'If you cannot do great things, do small things in a great way. \n~ Napoleon Hill',
		'Beware of monotony; it\'s the mother of all the deadly sins. \n~ Edith Wharton',
		'Nothing is really work unless you would rather be doing something else. \n~ J.M.Barrie',
		'Be patient with yourself. Self-growth is tender; it\'s holy ground. There\'s no greater investment. \n~ Stephen Covey',
		'Without hustle, talent will only carry you so far. \n~ Gary Vaynerchuk',
		'Working hard for something we don\'t care about is called stressed; working hard for something we love is called passion. \n~ Simon Sinek',
		'I\'d rather regret the things I\'ve done than regret the things I haven\'t done. \n~ Lucille BallMotivational quote by Lucille Ball',
		'I didn\'t get there by wishing for it or hoping for it, but by working for it. \n~ Estée Lauder',
		'Always do your best. What you plant now, you will harvest later. \n~ Og Mandino',
		'The key to life is accepting challenges. Once someone stops doing this, he\'s dead. \n~ Bette Davis',
		'Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable when you try something new. \n~ Brian Tracy',
		'Challenges are what make life interesting and overcoming them is what makes life meaningful. \n~ Joshua J. MarineMotivational quote by Joshua J. Marine',
		'Don\'t let the fear of losing be greater than the excitement of winning. \n~ Robert Kiyosaki',
		'How dare you settle for less when the world has made it so easy for you to be remarkable? \n~ Seth Godin',
		'Energy and persistence conquer all things. \n~ Benjamin Franklin',
		'Perseverance is failing 19 times and succeeding the 20th. \n~ Julie Andrews',
		'Failure after long perseverance is much grander than never to have a striving good enough to be called a failure. \n~ George Eliot',
		'The secret of joy in work is contained in one word -- excellence. To know how to do something well is to enjoy it. \n~ Pearl Buck',
		'Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. \n~ Dale Carnegie',
		'Action is the foundational key to all success. \n~ Pablo Picasso',
		'The ladder of success is best climbed by stepping on the rungs of opportunity. \n~ Ayn Rand',
		'Formula for success: rise early, work hard, strike oil. \n~ J. Paul Getty',
		'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will. \n~ Vince Lombardi',
		'Obstacles are those frightful things you see when you take your eyes off your goal. \n~ Henry Ford',
		'It is your determination and persistence that will make you a successful person. \n~ Kenneth J Hutchins',
		'You can waste your lives drawing lines. Or you can live your life crossing them. \n~ Shonda Rhimes',
		'Determine that the thing can and shall be done, and then we shall find the way. \n~ Abraham Lincoln',
		'Done is better than perfect. \n~ Sheryl Sandberg',
		'Don\'t ask if your dream is crazy, ask if it\'s crazy enough. \n~ Lena Waithe',
		'The act of doing something un-does the fear. \n~ Shonda Rhimes',
		'#1 make good decisions, #2 everything else. \n~ Rand Fishkin',
	];
}
